version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bank-db
    environment:
      POSTGRES_DB: sfk_bankdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql

  api:
    build: ./bank-api
    container_name: bank-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sfk_bankdata
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root